Repository saunah/saunah-backend, pull requests merged in 2022-04, with the labels that each got.

#15 Add auto generated api docs, in memory test DB
  .vscode/settings.json
  README.md
  build.gradle
  src/main/java/ch/saunah/saunahbackend/GreetingController.java
  src/main/java/ch/saunah/saunahbackend/SaunahBackendApplication.java
  src/main/java/ch/saunah/saunahbackend/configuration/SaunahBackendConfiguration.java
  src/main/java/ch/saunah/saunahbackend/model/User.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/java/ch/saunah/saunahbackend/SaunahBackendApplicationTests.java
  src/test/resources/application.properties
Labels: documentation, enhancement

#18 Doc/definition of done doc
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/k8s-deployment-notes.md
  docs/kubeconfig-example
  docs/pull_request_template.md
Labels: documentation

#30 Feature/configure saunah type
  build.gradle
  src/main/java/ch/saunah/saunahbackend/SaunahBackendApplication.java
  src/main/java/ch/saunah/saunahbackend/controller/SaunaController.java
  src/main/java/ch/saunah/saunahbackend/dto/SaunaTypeBody.java
  src/main/java/ch/saunah/saunahbackend/model/Sauna.java
  src/main/java/ch/saunah/saunahbackend/repository/SaunaRepository.java
  src/main/java/ch/saunah/saunahbackend/service/SaunaService.java
  src/test/java/ch/saunah/saunahbackend/service/SaunaServiceTest.java
Labels: sprint 3

#43 Patch/accept special characters password
  src/main/java/ch/saunah/saunahbackend/service/UserService.java
Labels: bug

#49 Feature/priecing sauna
  src/main/java/ch/saunah/saunahbackend/SaunahBackendApplication.java
  src/main/java/ch/saunah/saunahbackend/controller/PriceController.java
  src/main/java/ch/saunah/saunahbackend/dto/PriceBody.java
  src/main/java/ch/saunah/saunahbackend/dto/PriceResponse.java
  src/main/java/ch/saunah/saunahbackend/model/Price.java
  src/main/java/ch/saunah/saunahbackend/repository/PriceRepository.java
  src/main/java/ch/saunah/saunahbackend/service/PriceService.java
  src/test/java/ch/saunah/saunahbackend/service/PriceServiceTest.java
Labels: sprint 4
